import { z } from "zod";

// Expert definition - dynamically generated by Router
export const ExpertSchema = z.object({
  role: z.string().describe("Role name, e.g. 'Valuation Expert', 'Risk Analyst'"),
  needs: z.array(z.string()).describe("Required capabilities, e.g. ['finance', 'valuation']"),
  task: z.string().describe("Specific task description for this expert"),
});

export type Expert = z.infer<typeof ExpertSchema>;

// Router decision with dynamic experts
export const RouterDecisionSchema = z.object({
  experts: z.array(ExpertSchema).min(1).max(5),
  complexity: z.enum(["simple", "moderate", "complex"]),
  debate: z.boolean().optional().default(false),
  reason: z.string(),
});

export type RouterDecision = z.infer<typeof RouterDecisionSchema>;
